Fix scripts
Signed-off-by: Gabriel Lanata <gabriel@lanata.me>

diff --git a/bin/pr-quick-submit b/bin/pr-quick-submit
--- a/bin/pr-quick-submit
+++ b/bin/pr-quick-submit
@@ -49,7 +49,6 @@ while [[ $# -gt 0 ]]; do
             shift
         fi
 
-
         # if [[ ! "${2,,}" =~ ^(master|main)$ ]]; then
         #     base_branch="$2"
         # fi
@@ -71,13 +70,9 @@ while [[ $# -gt 0 ]]; do
         verbose=false
         shift
         ;;
-    -*)
-        echo "Unknown option $1"
-        exit 1
-        ;;
     *)
-        positional_args+=("$1") # save positional args
-        shift
+        echo "Error: Unknown argument '$1'"
+        exit 1
         ;;
     esac
 done
@@ -100,8 +95,7 @@ if [[ -z "$title" ]]; then
 fi
 
 # Fill the args
-commit_args=()
-pr_args=()
+declare -a commit_args=()
 
 if [[ -n "$body" ]]; then
     commit_args+=("-m" "$body")
@@ -128,7 +122,7 @@ run_with_env() {
 
 git commit --no-edit -m "$title" "${commit_args[@]}"
 if [[ -n "$head_sha" ]]; then
-    run_with_env git-submitpr "$head_sha" --base "$base_branch" "${pr_args[@]}" "${positional_args[@]}"
+    run_with_env git-submitpr "$head_sha" --base "$base_branch"
 else
-    run_with_env git-submitpr --base "$base_branch" "${pr_args[@]}" "${positional_args[@]}"
+    run_with_env git-submitpr --base "$base_branch"
 fi
diff --git a/bin/pr-quick-update b/bin/pr-quick-update
--- a/bin/pr-quick-update
+++ b/bin/pr-quick-update
@@ -52,8 +52,8 @@ while [[ $# -gt 0 ]]; do
         exit 1
         ;;
     *)
-        positional_args+=("$1") # save positional args
-        shift
+        echo "Error: Unknown argument '$1'"
+        exit 1
         ;;
     esac
 done
@@ -88,7 +88,6 @@ fi
 
 # Fill the args
 commit_args=()
-pr_args=()
 
 if [[ "$signoff" == true ]]; then
     commit_args+=("--signoff")
@@ -125,4 +124,4 @@ fi
 echo "Base SHA: $base_sha of $base_branch"
 
 run_with_env git commit --no-edit -m "$title" "${commit_args[@]}"
-run_with_env git-updatepr "$base_sha" "${pr_args[@]}" "${positional_args[@]}"
+run_with_env git-updatepr "$base_sha"
